### PR TITLE
Numerous Fixes

### PR DESCRIPTION
**Pull request by Ben-Kerman**
Here's some things I'm not sure about:

1. These cultures are defined twice in different groups:  
`sudanese` in `semitic` and `east_african`  
`maures` in `semitic` and `west_african`
1. The following files contain references to undefined regions/states:  
`decisions/Grossdeutschland.txt`, `events/HRE - 410000.txt`, `events/Liberal Kingdom of Germany-1231XX.txt`: HEK_568, MEC_544  
`decisions/Baltic.txt`, `decisions/NGF.txt`, `decisions/North Germany.txt`: HEK_568  
`events/Ameriga events.txt`: CHL_2327
1. There's a lot of duplicate events in and between `Amazonia.txt` and `Ameriga events.txt`
1. What's the point of these :  
`decisions/setup.txt`  
`decisions/TUR.txt/bosphorus_canal`  
`events/Tobefair - 919919.txt`
1. There's some `province_id` expressions in `decisions/China.txt/form_china_return/effect`, can those be removed?
1. Iirc from playing, there seem to be some leftover state-based election events from before those were made countrywide, remove them?
1. These event files still contain a lot from vanilla Vic2/PDM:  
`AssimilationTroubles.txt`  
`LiberalRevolutions.txt`  
`NationalUnification.txt`  
`NationalValues.txt`  
`NationalistMovements.txt`  
`PanNationalists.txt`  
`Revolution_Event.txt`  
`Scramble for Africa.txt`  
`VassalRebellion.txt`  
`newEvents.txt`
1. There's *a ton* of missing leader traits:  
amateur_surveyor:	Background  
`brave`:				Personality  
`calm`:				Personality  
`choleric`:			Personality  
`debutante`:		Background  
`disillusioned`:		ersonality  
`doughty`:			Personality  
`earnest`:			Personality  
`elder_statesman`:	Background  
`entrepreneur`:		Background  
`gambler`:			Background  
`generals_aide`:	Personality  
`gregarious`:		Personality  
`humanitarian`:		Personality  
`hussar_school`:	Background  
`intuitive`:		Personality  
`inventor`:			Background  
`lazy`:				Personality  
`machiavellian`:	Personality  
`medical_man`:		Background  
`modest`:			Personality  
`pragmatic`:		Personality  
`quixotic`:			Personality  
`tactful`:			Personality  
`tyrant`:			Personality
1. There's some countries with the undefined `midiwiwin` and `teotl` as state religion.
1. The history file for Rapa Nui has the undefined `declare_neutrality` decision.  
Same with `TUS_setup` for Etruria.
1. `ARC - Arcadia.txt` and `Ameriga decisions.txt` have invalid tech requirements since they refer to tech groups.
1. Many untriggered events:  
`Ameriga events.txt`: 775422  
`archaeology.txt`: 201007  
`councilITALY.txt`: 124208, 124207  
`GreatWar_Events.txt`: 96060, 96061  
`Liberal Kingdom of Germany-1231XX.txt`: 123107, 123109 (North German United Front)  
`Revolution_Event.txt`: 800147  
`Valois.txt`: 110630 (start of a chain)
1. Non-vanilla province history conflict: `austria/612 - Innsbruck.txt` vs. `germany/612 - Innsbruck.txt`  
The one in `germany` needs to go, according to vanilla file structure.
1. Some rebels that otherwise keep the current government type switch `merchant_republic` and `theocracy` to `democracy`. Is this intended?

### CODE REVIEW

**Comment by Pergame35** [comment]
1) both should be removed from east and west African groups
4) they are necessary for the Bosphorus strait to act like a Canal
5) Nope, you shouldn't need Treaty ports to form China
6) Nope just adapt their % so they don't change half the country to their issue 
7) not understood
9)change them either to Catholic/Protestant/Animism 
14) sure 
15) which one ? 
Also reactionaries should not change feudal to absolute

**Comment by Ben-Kerman** [comment]
1: Done.

4: The one in `TUR.txt`, sure, but setup.txt just adds influence for the Dual Monarchy over Navarra, which is already done in `history\units\DUA_oob.txt`. Also, neither decision can be taken.  
Most of what `Tobefair - 919919.txt` does can be done through history files, too.

5: I removed them now.

6: Will do.

7: I mean that they still have lots of references to countries, cultures, etc. that Divergences removes.

9: OK.

13: Done.

14: `nationalist_rebels` and `pan_nationalist_rebels`

**Comment by Pergame35** [comment]
Don't remove the "existing_countries" flag, otherwise there is an event at launch that says that it just became independent, because it doesn't have the flag. 

Also why the change to Etrurian first event ? They give background on the country to the player 
Also I don't understand why you changed some things like : "280 = { change_province_name = "Neufchâtel Sur Tyne" }" to "280 = { change_province_name = "Neufch�tel Sur Tyne" }"
Also the Navarran influence doesn't work with the OOB hence the setup decision

**Comment by Ben-Kerman** [comment]
I moved everything related to setting up a game to decisions/setup.txt, which is automatically activated at the start of the game through Rapa Nui's history file. This decision does the following:

* Set the existing_country flag for every country that exists at the start (this means you don't get the independence event, all other occurences of setting or checking that flag were completely redundant, as far as I can tell)
* Set the opened_society flag for every appropriate country
* Set the feudal flag for every feudal monarchy
* Turn every civilized feudal monarchy into an absolute one
* Give Etruria its starting event
* Activate the Bosphorus strait (not commited yet)

I deleted the events (and decision) that did that before, with the exception of the Etrurian event, which is now triggered only.  
I think this is a much cleaner solution than before, because it happens instantly on starting a game, without having to wait for the events to fire.

Some files were encoded in UTF-8 even though they didn't need to be, so I changed them to ANSI, which afaik Vic2 handles better. For some reason the GitHub difference view can't read ANSI characters, but if you look into the actual file, it's still the correct charactcer.

For me Navarra is still in DUA's sphere with 50 influence even though I removed the decision.

**Comment by Ben-Kerman** [comment]
Also, should Aragon get the south of Oran and Constantine as cores? there was a guy complaining about that on the forum.

**Comment by Pergame35** [comment]
Well if that works I don't have anything to say :p 
You could add it to the Latin Empire decisions indeed

**Comment by Ben-Kerman** [comment]
I tried fixing most untriggered events (did I get that right?), but I'm not quite sure what to do with "Installation of a sister-republic" (id = 110630) in Valois.txt.

You also should really look through these event files at some point and delete everything from normal PDM/unmodded Vic2 that doesn't work in DoD anymore: (from msot to least issues)

1. AssimilationTroubles.txt
1. PanNationalists.txt
1. Scramble for Africa.txt
1. Revolution_Event.txt
1. NationalUnification.txt

For example there's an event chain about a Hungarian revolt against Austria in one of those, and an event resolving pan-nationalist victory in Scandinavia. Most issues are about non-existing culture groups and cultures, though.  
Currently those files easily account for 80% of the non-graphics related event issues the validator detects.

**Comment by Pergame35** [comment]
Well I'd have to test it once I merge the branch, changing prestige in history files is not the most hardous task

**Pull request merged**
