### PR TITLE
Caliphate Uniqueness

### PR DESCRIPTION
**Pull request by Lys0gen**
Please read the description of the commit and consider whether this should be part of the mod. I understand if you don't deem it fitting, but perhaps you like the idea.

### CODE REVIEW

**Comment by Capitanloco6** [comment]
I like the sound of this! Sorry that I didn't respond earlier. I will first commit some of my own stuff that is WIP, then I'll merge your Arabia improvements after making sure there are no conflicts

**Comment by Capitanloco6** [comment]
Having looked into it, it seems that the modifier "recent_jihad duration" is missing. What did you intend for it?

**Comment by Lys0gen** [comment]
Oops, forgot to upload event_modifiers.txt


recent_jihad = {
	population_growth = -0.01
	pop_militancy_modifier = 0.1
	non_accepted_pop_consciousness_modifier = 0.05
	icon = 16
}

**Comment by Capitanloco6** [comment]
By the way, did you localise the caliphate events? If not I can do that tomorrow and push the update

**Comment by Lys0gen** [comment]
Ahh sorry, had forgotten that file as well. Hope I didn't waste too much of your time making you look for it

**Comment by Capitanloco6** [comment]
No problem, the new Caliphate stuff has been included in today's update (I feel it's easier than merging branches). Thanks for coding this! I had fun testing it.

**Pull request closed without merging**
