### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Taior**

### CODE REVIEW

**Comment by Ben-Kerman** [comment]
I'm curious what the issues with the file names were? I never had any problems with them.

**Comment by Taior** [comment]
2017-03-18-140233_1920x1080_scrot
This, for example. Also I've seen "San-Francisco Earthquake" instead of "Sanbao Earthquake" once.

**Comment by Ben-Kerman** [comment]
Are you sure you have an up-to-date .mod file? I get exactly the same results as in the screenshot if I remove `replace_path = "localisation"` from mine.

**Comment by Taior** [comment]
Sorry, you're right. This problem was completely on my side. I didn't expect that .mod file will ever change.

**Pull request merged**
